app/urls.py
from django.urls import path
from . import views as app_views

app_name = 'app'
urlpatterns = [
    path('',app_views.IndexView.as_view(),name = 'home'),
    path('product/<int:pk>/detail/',app_views.ProductDetailView.as_view(),name = 'detail'),
    path('cart/',app_views.CartView.as_view(),name = 'cart'),
    path('add/cart/',app_views.AddItemToCartView.as_view(),name = 'add_cart'),
    path('decrease/cart/',app_views.DecreaseCartItemQuantityView.as_view(),name = 'decrease'),
    path('increase/cart/',app_views.IncreaseCartItemQuantityView.as_view(),name = 'increase'),
    path('delete/cart/',app_views.DeleteCartItemView.as_view(),name = 'delete'),
    path('checkout/',app_views.CheckoutView.as_view(),name = 'checkout'),
    path('orders/',app_views.OrdersView.as_view(),name = 'orders'),
    path('order/<int:pk>/detail/',app_views.OrderDetailView.as_view(),name = 'order_detail'),
    path('search/',app_views.SearchResultsView.as_view(),name = 'search'),
    path('newsletters/',app_views.NewsLettersView.as_view(),name = 'newsletters')
]

control/urls.py
from django.urls import path
from . import views as control_views

app_name = 'control'
urlpatterns = [
    path('home/',control_views.AdminHomeView.as_view(),name = 'admin_home'),
    path('product/<int:pk>/detail/',control_views.AdminProductDetailView.as_view(),name = 'admin_product_detail'),
    path('',control_views.AdminSigninView.as_view(),name = 'admin_signin'),
    path('admin/logout/',control_views.LogoutAdminView.as_view(),name = 'logout_admin'),
    path('add/product/',control_views.AdminAddProductView.as_view(),name = 'add_product'),
    path('edit/product/<pk>/',control_views.AdminUpdateProductView.as_view(),name = 'update_product'),
    path('delete/product/',control_views.AdminRemoveProductView.as_view(),name = 'delete_product'),
]

wintrust2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('central/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('user.urls')),
    path('admin/', include('control.urls')),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name = 'user/password_reset_confirm.html'
        ),
        name = 'password_reset_confirm'),
    path(
        'password-reset-done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name = 'user/password_reset_done.html'
        ),
        name = 'password_reset_done'),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name = 'user/password_reset_complete.html'
        ),
        name = 'password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from PIL import Image

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length = 100)
    price = models.DecimalField(max_digits = 1000,decimal_places =2)
    description = models.TextField(max_length = 500)
    image1 = models.ImageField(upload_to = 'product_images/')
    image2 = models.ImageField(upload_to = 'product_images/',default = 'default.png')
    image3 = models.ImageField(upload_to = 'product_images/',default = 'default.png')
    
    def save(self):
        """ This function changes the resolution of the image before saving it """
        super().save()
        images = [self.image1,self.image2,self.image3]
        for img in images:
            new_img = Image.open(img.path)
            if img.width > 500 or img.height > 500:
                new_img= new_img.resize((500,500))
                new_img.save(img.path)
    
    def active_images(self):
        """ This function returns all the active images in the product """
        return [img for img in [self.image1,self.image2,self.image3] if img]
    
    def get_absolute_url(self):
        return reverse("control:admin_home")
        
                
    def __str__(self):
        return f"{self.name}"


class Cart(models.Model):
    """ This stores the table for the users cart """
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    
    def __str__(self):
        return f"{self.user.username}'s Cart"

class CartItems(models.Model):
    """ This is responsible for recording the items in the users cart """
    cart = models.ForeignKey(Cart,on_delete = models.CASCADE)
    product = models.ForeignKey(Product,on_delete = models.CASCADE)
    quantity = models.SmallIntegerField(default = 1)
    
    def __str__(self):
        return f"{self.product.name} in {self.cart.user.username}'s Cart"

class NewsLetters(models.Model):
    """ This model stores all the emails that will be used to send newsletters """
    email = models.EmailField()
    
    def __str__(self):
        return self.email

class OrderItem(models.Model):
    order = models.ForeignKey('Order',on_delete = models.CASCADE,null = True)
    product = models.ForeignKey(Product,on_delete = models.SET_NULL,null = True)
    quantity = models.PositiveSmallIntegerField(default = 0)

    def __str__(self):
        return f"Order Item"
    
class Order(models.Model):
    """ This class takes in all the orders that a user has made """
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    delivered = models.BooleanField(default = False)
    date = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return f"{self.user.username}'s Orders"

    def items_ordered(self):
        return sum([item.quantity for item in self.orderitem_set.all()])

class BillingAddress(models.Model):
    """ This model stores the billing address of an order """
    order = models.OneToOneField(Order,on_delete = models.CASCADE,null = True)
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    company_name = models.CharField('Company Name (Optional)',max_length = 100,null = True,blank = True)
    state_or_country = models.CharField("State/Country",max_length = 100)
    town_or_city = models.CharField("Town/City",max_length = 100)
    phone = models.CharField(max_length = 50)
    email = models.EmailField()
    post_or_zipcode = models.CharField("Postcode/ZIP",max_length = 50)
    
    def __str__(self):
        return f"Order {self.order.id} Billing Address"
    
class Payment(models.Model):
    """ This is a model that stores payment details of a transaction """
    order = models.OneToOneField(Order,on_delete = models.CASCADE)
    reference = models.CharField(max_length = 100)
    amount = models.DecimalField(max_digits = 20,decimal_places = 2)
    
    def __str__(self):
        return f"Payment for Order {self.order.id}"

control/models.py
from django.db import models

# Create your models here.

control/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponseRedirect,JsonResponse
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.views import View,generic
from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required,user_passes_test
from app.models import Product

# Create your views here.
    
class AdminSigninView(View):
    """ This class allows the admininstrator to signin """
    template_name = 'control/admin_signin.html'
    
    def get(self,request,*args,**kwargs):
        return render(request,self.template_name)
    
    def post(self,request,*args,**kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        context = {}
        try:
            user = authenticate(username = username,password = password)
            if user.is_superuser:
                login(request,user)
                return HttpResponseRedirect(reverse('control:admin_home'))
            else:
                context['error'] = 'You are not an admin.'
        except AttributeError:
            context['error'] = 'Invalid credentilals. Try Again.'
        return render(request,self.template_name,context)


    
class LogoutAdminView(View):
    """ This class logouts an admin """
    
    def dispatch(self,request,*args,**kwargs):
        logout(request)
        return redirect('control:admin_signin')
    
class AdminHomeView(UserPassesTestMixin,LoginRequiredMixin,generic.ListView):
    """ This class is responsible for displaying the landing page for the admin """
    model = Product
    template_name = 'control/index.html'
    context_object_name = 'goods'
    
    def test_func(self,*args,**kwargs):
        return self.request.user.is_superuser
    
    def get_login_url(self,*args,**kwargs):
        return reverse('control:admin_signin')
        
        
class AdminAddProductView(UserPassesTestMixin,LoginRequiredMixin,generic.CreateView):
    """ This allows the admin to add a new product """
    model = Product
    fields = ['name','price','image1','image2','image3','description']
    template_name = 'control/product_form.html'
    
    def test_func(self,*args,**kwargs):
        return self.request.user.is_superuser
    
    def get_login_url(self,*args,**kwargs):
        return reverse('control:admin_signin')
    
class AdminProductDetailView(UserPassesTestMixin,LoginRequiredMixin,generic.DetailView):
    """ This class displays the details of a product """
    model = Product
    context_object_name = 'good'
    template_name = 'control/products_detail.html'
    
    def test_func(self,*args,**kwargs):
        return self.request.user.is_superuser
    
    def get_login_url(self,*args,**kwargs):
        return reverse('control:signin')
    
    
class AdminUpdateProductView(UserPassesTestMixin,LoginRequiredMixin,generic.UpdateView):
    """ This allows the admin to add a new product """
    model = Product
    fields = ['name','price','image1','image2','image3','description']
    template_name = 'control/product_form.html'
    context_object_name = 'good'
    
    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['update'] = True
        return context
    
    def test_func(self,*args,**kwargs):
        return self.request.user.is_superuser
    
    def get_login_url(self,*args,**kwargs):
        return reverse('control:admin_signin')
    
        
class AdminRemoveProductView(View):
    """ This view removes a product """
    
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    @method_decorator(login_required(login_url = "/admin/"))
    def get(self,request,*args,**kwargs):
        product_id = int(request.GET.get('productId'))
        product = get_object_or_404(Product,id = product_id)
        product.delete()
        data = {
            'product_id': product_id
        }
    
        return JsonResponse(data)

control/templates/control/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'control/bootstrap.min.css' %}">
    <style>
        /* width */
        ::-webkit-scrollbar {
          width: 8px;
        }

        /* Track */
        ::-webkit-scrollbar-track {
          background: #f1f1f1;
        }

        /* Handle */
        ::-webkit-scrollbar-thumb {
          background: #888;
        }

        /* Handle on hover */
        ::-webkit-scrollbar-thumb:hover {
          background: #333333;
        }
        body{
            margin: auto;
        }
        /* Navbar Designs */
        nav{
            padding:10px;
            background: #333333;
            width: 100%;
        }
        nav a{
            text-decoration: none;
            font: 20px verdana;
            color: #159fdc;
        }
        nav a:hover{
            text-decoration: none;
        }
        nav ul{
            margin: 0px;
            list-style-type: none;
            padding: 0px;
            float: right;
        }
        nav ul li a{
            font-size: 16px;
            padding: 5px 10px 0px 10px;
        }
        nav ul li a:hover{
            color: rgba(255,255,255,.8)
        }
    </style>
    {% block head %}
    {% endblock %}
</head>
<body>
    <div class="container">
        <nav class="fixed-top">
            <a href="{% url 'control:admin_home' %}" >OGOCANDO Commodities (Admin)</a>
            <ul>
                <li><a href="{% url 'control:logout_admin' %}">
                   <img width="16px" src="{% static 'control/images/logout.png' %}" alt="">
                    Logout
                </a></li>
            </ul>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    <script src="{% static 'control\jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'control\bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'control\Chart.bundle.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

control/templates/control/index.html
{% extends 'control/base.html' %}
{% load static %}


{% block head %}
    <title>Admin Home</title>
    <style>
        a:hover{
            text-decoration: none;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container" style = 'margin-top: 70px;'>
        <h2 class="text-muted d-flex justify-content-between">
            Products
            <div>
                <a href="{% url 'control:add_product' %}" class="btn btn-dark">Add Product</a>
            </div>
        </h2><hr/>
        <div class="row">
            {% for good in goods %}
                <div class="col-6 col-sm-4 col-md-3 mt-2">
                    <div class="card" style="box-shadow: 0px 2px 5px rgba(0,0,0,.3);">
<!--                        <a href="{% url 'control:admin_product_detail' good.pk %}">-->
                           <img height="140px" src="{{ good.image1.url }}" class="card-img-top" alt="">
<!--                        </a>-->
                        <div class="card-body">
<!--                           <a href="{% url 'control:admin_product_detail' good.pk %}">-->
                               <p class="text-center">{{ good.name }}</p>
<!--                           </a>-->
                            <a href="{% url 'control:update_product' good.pk %}" class="btn-block btn btn-sm btn-primary">Edit</a>
                            <button data-toggle="modal" id="{{ good.id }}" data-target="#deleteModal" class="btn-block btn btn-sm btn-danger delete">Delete</button>
                        </div>
                    </div>
                </div>    
            {% endfor %}
        </div>
        <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title text-danger" id="deleteModalLabel">Delete Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Are you sure you want to delete this product 
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Cancel</button>
                <button type="button" id="permDelete" class="btn btn-danger btn-sm">Delete</button>
              </div>
            </div>
          </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        let currentProductId = undefined;
        // A function that deletes a product
        let deleteProduct = () => {
            $('.delete').click(function(){
                currentProductId = $(this).attr('id');
                console.log(currentProductId)
            });
            
            // Permenetly Delete Product
            $('#permDelete').click(function(){
                $(this).attr('data-dismiss','modal');
                console.log(currentProductId)
                // Make an ajax request to delete product
                $.ajax({
                    url: "{% url 'control:delete_product' %}",
                    data: {
                        'productId' : currentProductId
                    },
                    dataType: 'json',
                    success: function(data){
                        $(`#${data['product_id']}`).parent().parent().parent().fadeOut(function(){
                            // Remove the product
                            $(this).remove();
                        })
                    }
                });
            });
        }
        deleteProduct();
    </script>
{% endblock %}

control/templates/control/product_form.html
{% extends 'control/base.html' %}
{% load static %}


{% block head %}
    <title>New Product</title>
    <style>
        /* Main Container - Preview */
        #qty-container p{
            display: inline-block;
        }
        #qty-container p:nth-child(2){
            border: thin solid rgba(0,0,0,.125);
            padding: 5px;
            user-select: none;
        }
        #qty-container p:nth-child(2) span{
            padding: 0px 15px;
            cursor: pointer;
            font-size: 18px;
        }
        #qty-container p:nth-child(2) span:hover{
            color: #159fdc
        }
        #add{
            background: #159fdc;
            padding: 5px 0px;
            color: white;
            border: thin solid #159fdc;
            text-align: center;
            transition: all .3s ease-in-out;
            cursor: pointer;
        }
        #add:hover{
            color: #159fdc;
            background: white;
        }
        #other-images-container{
            text-align: center;
            display: grid;
            grid-template-columns: repeat(3,1fr)
        }
        #other-images-container > img:first-child{
            opacity: 1;
            border: thin solid #159fdc;
        }
        #other-images-container > img{
            cursor: pointer;
            width: 100%;
            opacity: .7;
            transition: all .1s ease-in-out;
        }
        #other-images-container > img:hover{
            opacity: 1;
        }
        /* Program */
        form input[type = 'submit']{
            background: #159fdc;
            border-radius: 2px;
            color: #333333;
            transition: all .2s ease-in-out;
        }
        form input[type = 'submit']:hover{
            color: #159fdc;
            background: #333333;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container" style="margin-top: 80px;">
      <div class="row">
          <div class="col-sm-5">
            <h4 class="text-muted">Preview</h4><hr>
           <!-- Preview -->
           {% if update %}
                <div class="row" id="main-container">
                    <div class="col-12">
                        <img id="main-image" width="100%" height="300px;" src="{{ good.image1.url }}" alt="">
                        <div id="other-images-container">
                            {% for img in good.active_images %}
                                <img src="{{ img.url }}" alt="">
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-12">
                        <h1 class="text-center" style="font-size: 1.6rem;color: #333333;font-weight: 400;" id="product-name">{{ good.name }}</h1>
                        <h1 class="text-center" style="font-size: 1.6rem;color: #159fdc;font-weight: 400;" id="product-price">GHC {{ good.price }}</h1>
                        <p class="text-muted text-center" id="product-description">{{ good.description }}</p>
                        <div class="text-center" id="qty-container">
                            <p class="text-muted mr-3">Qty:</p>
                            <p class="text-muted">
                                <span id="decrease">-</span>
                                <span id = 'qty'>1</span>
                                <span id="increase">+</span>
                            </p>
                        </div>
                        <p id="add">ADD TO CART</p>
                    </div>
                </div>
            {% else %}
                <div class="row" id="main-container">
                    <div class="col-12">
                        <img id="main-image" width="100%" height="300px;" src="{% static 'app/images/image1.png' %}" alt="Main Image">
                        <div id="other-images-container">
                            <img src="{% static 'app/images/image1.png' %}" alt="Image 1">
                            <img src="{% static 'app/images/image2.png' %}" alt="Image 2">
                            <img src="{% static 'app/images/image3.png' %}" alt="Image 3">
                        </div>
                    </div>
                    <div class="col-12">
                        <h1 class="text-center" style="font-size: 1.6rem;color: #333333;font-weight: 400;" id="product-name">Poduct Name</h1>
                        <h1 class="text-center" style="font-size: 1.6rem;color: #159fdc;font-weight: 400;" id="product-price">Product Price</h1>
                        <p class="text-muted text-center" id="product-description">Product Description</p>
                        <div class="text-center" id="qty-container">
                            <p class="text-muted mr-3">Qty:</p>
                            <p class="text-muted">
                                <span id="decrease">-</span>
                                <span id = 'qty'>1</span>
                                <span id="increase">+</span>
                            </p>
                        </div>
                        <p id="add">ADD TO CART</p>
                    </div>
                </div>
            {% endif %}
          </div>
          <div class="col-sm-7">
              <!-- Program -->
            <h4 class="text-muted mt-5 mt-sm-0">Program</h4><hr>
            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- Name -->
                <div class="form-group">
                    {{form.name.label_tag}}
                    {{form.name}}
                </div>
                <!-- Price -->
                <div class="form-group">
                    {{form.price.label_tag}}
                    {{form.price}}
                </div>
                <!-- Image 1 -->
                <div class="form-group">
                    <label for="">Image 1:</label>
                    <p class="text-info small m-auto" id="image1-info">No File Uploaded</p>
                    <div class="input-group input-group-sm">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="id_image1">Upload</span>
                        </div>
                        <div class="custom-file">
                            <input type="file" name="image1" accept="image/*" class="custom-file-input" id = 'id_image1'>
                            <label for="id_image1" class="custom-file-label">Choose File</label>
                        </div>
                    </div>
                </div>
                <!-- Image 2 -->
                <div class="form-group">
                    <label for="">Image 2:</label>
                    <p class="text-info small m-auto" id="image2-info">No File Uploaded</p>
                    <div class="input-group input-group-sm">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="id_image2">Upload</span>
                        </div>
                        <div class="custom-file">
                            <input type="file" accept="image/*" name="image2" class="custom-file-input" id = 'id_image2'>
                            <label for="id_image2" class="custom-file-label">Choose File</label>
                        </div>
                    </div>
                </div>
                <!-- Image 3 -->
                <div class="form-group">
                   <p class="text-info small m-auto" id="image3-info">No File Uploaded</p>
                    <label for="">Image 3:</label>
                    <div class="input-group input-group-sm">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="id_image3">Upload</span>
                        </div>
                        <div class="custom-file">
                            <input type="file" accept="image/*" name="image3" class="custom-file-input" id = 'id_image3'>
                            <label for="id_image3" class="custom-file-label">Choose File</label>
                        </div>
                    </div>
                </div>
                <!-- Description -->
                <p class="text-muted small m-auto" id="description-count"></p>
                <div class="form-group">
                    {{form.description}}
                </div>
                {% if update %}
                    <input type="submit" class="btn btn-block mt-3 mb-3" value="Save Changes">
                {% else %}
                    <input type="submit" value="Add Product" class="btn btn-block mt-3 mb-3">
                {% endif %}
            </form>
          </div>
      </div>
    </div>
{% endblock %}
{% block javascript %}
    <script>
//        let productImage = document.getElementById('id_image');
        
        // A function that runs when the page loads
        let init = () => {
            // Show the number of characters in the textbox
            let descriptionValue = $('#id_description').val().length;
            $('#description-count').text(`${descriptionValue}/500`);
            
            // Add some boostrap styling to the form
            $('#id_name, #id_price, #id_description').attr('class','form-control form-control-sm');
        }
        
        init()
        
        // A function that will be updating the preview section of the product
        let updatePreview = () => {
            // Product Name
            $('#id_name').keyup(function(){
                let productNameValue = $(this).val();
                if(productNameValue){
                    $('#product-name').text(productNameValue);
                }
                else{
                    $('#product-name').text('Product Name');
                }
            });
            
            // Product Price
            $('#id_price').keyup(function(){
                let productPriceValue = $(this).val();
                let productPriceFilter = /^\d+(\.\d\d?)?$/;
                if(!productPriceFilter.test(productPriceValue) && productPriceValue){
                    let productPriceList = productPriceValue.split('.'); 
                    productPriceList[1] = productPriceList[1].slice(0,2);
                    $(this).val(productPriceList.join('.'));
                    productPriceValue = productPriceList.join('.');
                }
                if(productPriceValue){
                    $('#product-price').html(`GHC ${productPriceValue}`);
                }
                else{
                    $('#product-price').text('Product Price');
                }
            });
            
            // Product Description
            $('#id_description').keyup(function(e){
                let productDescriptionValue = $(this).val();
                let descriptionCount = $('#description-count');
                if(productDescriptionValue){
                    $("#product-description").text(productDescriptionValue);
                    if(productDescriptionValue.length < 501){
                        descriptionCount.text(`${productDescriptionValue.length}/500`);
                    }   
                    else{
                        $(this).attr('disabled','true');
                    }
                }
                else{
                    $('#product-description').text('Product Description');
                }
                if(e.key === 'Backspace'){
                    $(this).removeAttr('disabled');
                    descriptionCount.text(`${productDescriptionValue.length}/500`);
                }
            });
            
            // Product Image
            $('#id_product_image').change(function(){
                console.log(productImage.files)
                if(productImage.files[0]){
                    file = new FileReader();
                    file.onload = () => {
                        $('#preview-product-image').attr('src',file.result);
                    }
                    file.readAsDataURL(productImage.files[0]);
                }
            });
        }
        updatePreview();
        // A function that increases or decreases the quantity of an item
        let modifyQuantity = () => {
            // Increase Quantity
            $('#increase').click(function(){
                let qty = $('#qty');
                if(Number(qty.text()) + 1 < 100){
                    qty.text(`${Number(qty.text()) + 1}`)
                }
            });
            
            // Decrease Quantity
            $('#decrease').click(function(){
                let qty = $('#qty');
                if(Number(qty.text()) - 1 > 0){
                    qty.text(`${Number(qty.text()) - 1}`)
                }
            });
        }
        modifyQuantity()
        
        // A function that changes the image of the main product
        let changeImage = () => {
            let currentImageIndex = 0;
            $('#other-images-container img').click(function(){
                $('#other-images-container img').eq(currentImageIndex).css({'opacity':'.7','border':'none'});
                $(this).css({'opacity':'1','border':'thin solid #159fdc'});
                $('#main-image').attr('src',$(this).attr('src'));
                currentImageIndex = $('#other-images-container img').index($(this));
            });
        }
        
        changeImage()
        
        // A function that add some bootstrap to the normal file input
        let changedImage = () => {
            $('input[type = "file"]').change(function(){
                $(this).parent().parent().parent().find('p').first().text('File has been uploaded').attr('class','text-success small m-auto');
            });
        }
        changedImage()
        
    </script>
{% endblock %}