app/urls.py
from django.urls import path
from . import views as app_views

app_name = 'app'
urlpatterns = [
    path('',app_views.IndexView.as_view(),name = 'home'),
    path('product/<int:pk>/detail/',app_views.ProductDetailView.as_view(),name = 'detail'),
    path('cart/',app_views.CartView.as_view(),name = 'cart'),
    path('add/cart/',app_views.AddItemToCartView.as_view(),name = 'add_cart'),
    path('decrease/cart/',app_views.DecreaseCartItemQuantityView.as_view(),name = 'decrease'),
    path('increase/cart/',app_views.IncreaseCartItemQuantityView.as_view(),name = 'increase'),
    path('delete/cart/',app_views.DeleteCartItemView.as_view(),name = 'delete'),
    path('checkout/',app_views.CheckoutView.as_view(),name = 'checkout'),
    path('orders/',app_views.OrdersView.as_view(),name = 'orders'),
    path('order/<int:pk>/detail/',app_views.OrderDetailView.as_view(),name = 'order_detail'),
    path('search/',app_views.SearchResultsView.as_view(),name = 'search'),
    path('newsletters/',app_views.NewsLettersView.as_view(),name = 'newsletters')
]

user/urls.py
from django.urls import path,include
from django.contrib.auth import views as authviews
from . import views as user_views

app_name = 'user'
urlpatterns = [
    path('signin/',user_views.LoginUserView.as_view(),name = 'signin'),
    path('signup/',user_views.SignUpUser.as_view(),name = 'signup'),
    path('user/profile/',user_views.UserProfileView.as_view(),name = 'profile'),
    path('logout/',authviews.LogoutView.as_view(),name = 'logout'),
    path(
        'password-reset/',
        authviews.PasswordResetView.as_view(
            template_name = 'user/password_reset.html'
        ),
        name = 'password_reset'),
    
]

wintrust2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('central/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('user.urls')),
    path('admin/', include('control.urls')),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name = 'user/password_reset_confirm.html'
        ),
        name = 'password_reset_confirm'),
    path(
        'password-reset-done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name = 'user/password_reset_done.html'
        ),
        name = 'password_reset_done'),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name = 'user/password_reset_complete.html'
        ),
        name = 'password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from PIL import Image

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length = 100)
    price = models.DecimalField(max_digits = 1000,decimal_places =2)
    description = models.TextField(max_length = 500)
    image1 = models.ImageField(upload_to = 'product_images/')
    image2 = models.ImageField(upload_to = 'product_images/',default = 'default.png')
    image3 = models.ImageField(upload_to = 'product_images/',default = 'default.png')
    
    def save(self):
        """ This function changes the resolution of the image before saving it """
        super().save()
        images = [self.image1,self.image2,self.image3]
        for img in images:
            new_img = Image.open(img.path)
            if img.width > 500 or img.height > 500:
                new_img= new_img.resize((500,500))
                new_img.save(img.path)
    
    def active_images(self):
        """ This function returns all the active images in the product """
        return [img for img in [self.image1,self.image2,self.image3] if img]
    
    def get_absolute_url(self):
        return reverse("control:admin_home")
        
                
    def __str__(self):
        return f"{self.name}"


class Cart(models.Model):
    """ This stores the table for the users cart """
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    
    def __str__(self):
        return f"{self.user.username}'s Cart"

class CartItems(models.Model):
    """ This is responsible for recording the items in the users cart """
    cart = models.ForeignKey(Cart,on_delete = models.CASCADE)
    product = models.ForeignKey(Product,on_delete = models.CASCADE)
    quantity = models.SmallIntegerField(default = 1)
    
    def __str__(self):
        return f"{self.product.name} in {self.cart.user.username}'s Cart"

class NewsLetters(models.Model):
    """ This model stores all the emails that will be used to send newsletters """
    email = models.EmailField()
    
    def __str__(self):
        return self.email

class OrderItem(models.Model):
    order = models.ForeignKey('Order',on_delete = models.CASCADE,null = True)
    product = models.ForeignKey(Product,on_delete = models.SET_NULL,null = True)
    quantity = models.PositiveSmallIntegerField(default = 0)

    def __str__(self):
        return f"Order Item"
    
class Order(models.Model):
    """ This class takes in all the orders that a user has made """
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    delivered = models.BooleanField(default = False)
    date = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return f"{self.user.username}'s Orders"

    def items_ordered(self):
        return sum([item.quantity for item in self.orderitem_set.all()])

class BillingAddress(models.Model):
    """ This model stores the billing address of an order """
    order = models.OneToOneField(Order,on_delete = models.CASCADE,null = True)
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    company_name = models.CharField('Company Name (Optional)',max_length = 100,null = True,blank = True)
    state_or_country = models.CharField("State/Country",max_length = 100)
    town_or_city = models.CharField("Town/City",max_length = 100)
    phone = models.CharField(max_length = 50)
    email = models.EmailField()
    post_or_zipcode = models.CharField("Postcode/ZIP",max_length = 50)
    
    def __str__(self):
        return f"Order {self.order.id} Billing Address"
    
class Payment(models.Model):
    """ This is a model that stores payment details of a transaction """
    order = models.OneToOneField(Order,on_delete = models.CASCADE)
    reference = models.CharField(max_length = 100)
    amount = models.DecimalField(max_digits = 20,decimal_places = 2)
    
    def __str__(self):
        return f"Payment for Order {self.order.id}"

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

    

# The sign up form
class NewUser(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1']
        
class EditUserProfileForm(forms.ModelForm):
    """ This class is responsible for editing the details of the user """
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email']
        widgets = {
            'first_name': forms.TextInput(attrs = {
                'class': 'form-control form-control-sm ',
            }),
            'last_name': forms.TextInput(attrs = {
                'class': 'form-control form-control-sm ',
            }),
            'username': forms.TextInput(attrs = {
                'class': 'form-control form-control-sm ',
            }),
            'email': forms.EmailInput(attrs = {
                'class': 'form-control form-control-sm ',
            })
        }

user/views.py
# IMPORTS
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.views import View,generic
from app.models import Cart,NewsLetters
from .forms import NewUser,EditUserProfileForm
from app.views import important_info

# Create your views here.

class LoginUserView(LoginView):
    """ This class is reponsible for signin up users """
    template_name = 'user/forms_login.html'
    
    def get_success_url(self,*args,**kwargs):
        return reverse('app:home')

class SignUpUser(View):
    form_class = NewUser
    template_name = 'user/forms_signup.html'
    
    def get(self,request,*args,**kwargs):
        form = self.form_class()
        return render(request,self.template_name,{'form':form})
    
    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            user = get_object_or_404(User, username = form.cleaned_data.get('username'))
            # Create the cart for the user
            cart = Cart(user = user)
            cart.save()
            # Add the user's email to the news letters
            try:
                get_object_or_404(NewsLetters,email = form.cleaned_data.get('email'))
            except NewsLetters.DoesNotExist:
                news_letters = NewsLetters(email = form.cleaned_data.get('username'))
                news_letters.save()
            messages.success(request,f'You account has been succesfully created, you can sign in now.')
            return HttpResponseRedirect(reverse('user:signin'))
        return render(request,self.template_name,{'form':form})
    
class UserProfileView(generic.View):
    """ This class shows the profile of the user """
    form_class = EditUserProfileForm
    template_name= 'user/profile.html'
    
    @method_decorator(login_required(login_url = '/signin/' ))
    def get(self,request,*args,**kwargs):
        form = self.form_class(instance = request.user)
        context = {
            'form': form
        }
        important_info(self,context)
        return render(request,self.template_name,context)
    
    
    
    @method_decorator(login_required(login_url = '/sigin/' ))
    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST,instance = request.user)
        if form.is_valid and form.changed_data:
            print('I have been changed')
            print(form.changed_data)
            form.save()
            return HttpResponseRedirect(reverse('user:profile'))
        else:
            print('I have not been changed')
        
        context = {
            'form': form
        }
        important_info(self,context)
        return render(request,self.template_name,context)

user/templates/user/base.html
{% load static %}

<!DOCTYPE html>
<html lang="">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
    {% endblock head %}
</head>

<body>
   <div id="container">
        {% block content %}
        {% endblock %}
   </div>
   <script src="{% static 'user/jquery-3.4.1.min.js' %}"></script>
   {% block javascript %}
   {% endblock %}
</body>
</html>

user/templates/user/forms_login.html
{% extends 'user/base.html' %}
{% load static %}


{% block head %}
    <title>Sign In</title>
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles.css' %}"/>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <h1>OGOCANDO Commodities</h1>
        {% if messages %}
            {% for message in messages %}
                <div class="message">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {{ form.as_p }}
        <a href="{% url 'user:password_reset' %}" id="forgot">Forgot Password</a>
        <br/>
        <input type="submit" value = 'Sign In' /><br/>
        <span id="new-member">Not a member? <a href="{% url 'user:signup' %}"> Sign Up</a></span>
    </form>
    <script>
    </script>
{% endblock %}

user/templates/user/forms_signup.html
{% extends 'user/base.html' %}
{% load static %}


{% block head %}
    <title>Sign Up</title>
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles.css' %}"/>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <h1>OGOCANDO Commodities</h1>
        {{ form.as_p }}
        <input type="submit" value = 'Sign Up'/><br/>
        <span id="new-member">Already a member? <a href="{% url 'user:signin' %}"> Sign In</a></span>
    </form>
    <script>
        
    </script>
{% endblock %}

user/templates/user/password_reset.html
{% extends 'user/base.html' %}
{% load static %}


{% block head %}
    <title>Sign In</title>
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles.css' %}"/>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <h1>OGOCANDO Commodities</h1>
        {{ form.as_p }}
        <br/>
        <input type="submit" value = 'Request Password Reset' /><br/>
    </form>
    <script>
    </script>
{% endblock %}

user/templates/user/password_reset_complete.html
{% extends 'user/base.html' %}
{% load static %}


{% block head %}
    <title>Sign In</title>
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles.css' %}"/>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <h1>Your password has been reset</h1>
        <span id="new-member"><a href="{% url 'user:signin' %}"> Sign In Here</a></span>
    </form>
    <script>
    </script>
{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends 'user/base.html' %}
{% load static %}


{% block head %}
    <title>Sign In</title>
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles.css' %}"/>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <h1>OGOCANDO Commodities</h1>
        {{ form.as_p }}
        <br/>
        <input type="submit" value = 'Reset Password' /><br/>
    </form>
    <script>
    </script>
{% endblock %}

user/templates/user/password_reset_done.html
{% extends 'user/base.html' %}
{% load static %}


{% block head %}
    <title>Sign In</title>
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles.css' %}"/>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <h1>An email has been sent to your account</h1>
    </form>
    <script>
    </script>
{% endblock %}

user/templates/user/profile.html
{% extends 'app/base.html' %}
{% load static %}

{% block head %}
    <title>User Profile</title>
    <style>
        /* Main Menu */
        #main-menu{
            width: calc(100% - 170px);
            margin: auto;
/*            height: 200px;*/
/*            background: lime;*/
            display: inline-block;
            position: relative;
            left: 160px;
            transition: all .2s ease-in-out;
        }
        #main-menu > form > div:last-child > button{
            color: #333333;
            background: #159fdc;
            transition: all .15s ease-in-out;
        }
        #main-menu > form > div:last-child > button:hover{
            color: #159fdc;
            background: #333333;
        }
        /* Side Menu */
        #side-menu{
            width: 150px;
            position: fixed;
            height: 100vh;
/*            border-right: thin solid rgba(0,0,0,.125);*/
            left: 0px;
            top: 120px;
/*            border: thin solid red;*/
            transition: all .2s ease-in-out;
        }
        #side-menu a{
            display: block;
            text-align: center;
            padding: 10px 0px;
            color: lightslategray;
            font-weight: 500;
        }
        #side-menu a:hover{
            text-decoration: none;
            color: #159fdc;
        }
        #side-menu #active{
            border-right: medium solid #159fdc;
            color: #159fdc;
        }
        #side-menu > a:not('.small-screen-item-link'):last-child{
            color: red;
        }
        #side-menu > a:not('.small-screen-item-link'):last-child:hover{
            color: red;
        }
        /* Hide Small Screen Icons */
        #side-menu a.small-screen-item-link{
            display: none;
        }
        
        /* Media query from 0px - 500px */
        @media only screen and (max-width:500px){
            /* Side Menu */
            #side-menu{
                width: 50px;
            }
            #side-menu h5, #side-menu a{
                display: none;
            }
            #side-menu > a.small-screen-item-link{
                display: block;
            }
            /* Main Menu */
            #main-menu{
                width: calc(100% - 60px);
                left: 55px;
            }
        }
    </style>
{% endblock %}
{% block content %}
    <div id="wrapper" style = 'margin-top: 120px;'>
        <div id="side-menu">
            <h5 class="text-center text-dark">User Profile</h5>
            <!-- Big Screen -->
            <a href="{% url 'user:profile' %}" id="active">User Info</a>
            <a href="{% url 'app:cart' %}">Cart &nbsp; <span class="badge badge-dark">{{ cart_items_count }}</span></a>
            <a href="{% url 'app:orders' %}">Orders &nbsp; <span class="badge badge-dark">{% firstof user.order_set.count '0' %}</span></a>
            <a href="{% url 'user:logout' %}" style="color: red;">Logout</a>
            <!-- Small Screen -->
            <a href="{% url 'user:profile' %}" class = 'small-screen-item-link' id="active" >
                <img width="40px" src="{% static 'app/images/user-profile.png' %}" alt="Profile">
            </a>
            <a href="{% url 'app:cart' %}" class = 'small-screen-item-link'>
               <img width="40px" src="{% static 'app/images/cart-small.png' %}" alt="Cart">
            </a>
            <a href="{% url 'app:orders' %}" class = 'small-screen-item-link' >
                <img width="40px" src="{% static 'app/images/order.png' %}" alt="Orders">
            </a>
            <a href="{% url 'user:logout' %}" class = 'small-screen-item-link' >
                <img width="40px" src="{% static 'app/images/logout-small.png' %}" alt="Logout">
            </a>
        </div>
        <div id="main-menu">
            <form action="." method="post" style="max-width: 800px;margin: auto;">
                {% csrf_token %}
                <div class="row no-gutters">
                    {% for field in form %}
                        <div class="col-sm-6 p-2">
                            <div class="form-group">
                                {{ field.label_tag }}
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div style = 'max-width: 400px;margin: 20px auto;'>
                    <button type="submit" class="btn btn-block"> Save Changes</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block javascript %}
{% endblock %}