app/urls.py
from django.urls import path
from . import views as app_views

app_name = 'app'
urlpatterns = [
    path('',app_views.IndexView.as_view(),name = 'home'),
    path('product/<int:pk>/detail/',app_views.ProductDetailView.as_view(),name = 'detail'),
    path('cart/',app_views.CartView.as_view(),name = 'cart'),
    path('add/cart/',app_views.AddItemToCartView.as_view(),name = 'add_cart'),
    path('decrease/cart/',app_views.DecreaseCartItemQuantityView.as_view(),name = 'decrease'),
    path('increase/cart/',app_views.IncreaseCartItemQuantityView.as_view(),name = 'increase'),
    path('delete/cart/',app_views.DeleteCartItemView.as_view(),name = 'delete'),
    path('checkout/',app_views.CheckoutView.as_view(),name = 'checkout'),
    path('orders/',app_views.OrdersView.as_view(),name = 'orders'),
    path('order/<int:pk>/detail/',app_views.OrderDetailView.as_view(),name = 'order_detail'),
    path('search/',app_views.SearchResultsView.as_view(),name = 'search'),
    path('newsletters/',app_views.NewsLettersView.as_view(),name = 'newsletters')
]

user/urls.py
from django.urls import path,include
from django.contrib.auth import views as authviews
from . import views as user_views

app_name = 'user'
urlpatterns = [
    path('signin/',user_views.LoginUserView.as_view(),name = 'signin'),
    path('signup/',user_views.SignUpUser.as_view(),name = 'signup'),
    path('user/profile/',user_views.UserProfileView.as_view(),name = 'profile'),
    path('logout/',authviews.LogoutView.as_view(),name = 'logout'),
    path(
        'password-reset/',
        authviews.PasswordResetView.as_view(
            template_name = 'user/password_reset.html'
        ),
        name = 'password_reset'),
    
]

wintrust2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('central/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('user.urls')),
    path('admin/', include('control.urls')),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name = 'user/password_reset_confirm.html'
        ),
        name = 'password_reset_confirm'),
    path(
        'password-reset-done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name = 'user/password_reset_done.html'
        ),
        name = 'password_reset_done'),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name = 'user/password_reset_complete.html'
        ),
        name = 'password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from PIL import Image

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length = 100)
    price = models.DecimalField(max_digits = 1000,decimal_places =2)
    description = models.TextField(max_length = 500)
    image1 = models.ImageField(upload_to = 'product_images/')
    image2 = models.ImageField(upload_to = 'product_images/',default = 'default.png')
    image3 = models.ImageField(upload_to = 'product_images/',default = 'default.png')
    
    def save(self):
        """ This function changes the resolution of the image before saving it """
        super().save()
        images = [self.image1,self.image2,self.image3]
        for img in images:
            new_img = Image.open(img.path)
            if img.width > 500 or img.height > 500:
                new_img= new_img.resize((500,500))
                new_img.save(img.path)
    
    def active_images(self):
        """ This function returns all the active images in the product """
        return [img for img in [self.image1,self.image2,self.image3] if img]
    
    def get_absolute_url(self):
        return reverse("control:admin_home")
        
                
    def __str__(self):
        return f"{self.name}"


class Cart(models.Model):
    """ This stores the table for the users cart """
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    
    def __str__(self):
        return f"{self.user.username}'s Cart"

class CartItems(models.Model):
    """ This is responsible for recording the items in the users cart """
    cart = models.ForeignKey(Cart,on_delete = models.CASCADE)
    product = models.ForeignKey(Product,on_delete = models.CASCADE)
    quantity = models.SmallIntegerField(default = 1)
    
    def __str__(self):
        return f"{self.product.name} in {self.cart.user.username}'s Cart"

class NewsLetters(models.Model):
    """ This model stores all the emails that will be used to send newsletters """
    email = models.EmailField()
    
    def __str__(self):
        return self.email

class OrderItem(models.Model):
    order = models.ForeignKey('Order',on_delete = models.CASCADE,null = True)
    product = models.ForeignKey(Product,on_delete = models.SET_NULL,null = True)
    quantity = models.PositiveSmallIntegerField(default = 0)

    def __str__(self):
        return f"Order Item"
    
class Order(models.Model):
    """ This class takes in all the orders that a user has made """
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    delivered = models.BooleanField(default = False)
    date = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return f"{self.user.username}'s Orders"

    def items_ordered(self):
        return sum([item.quantity for item in self.orderitem_set.all()])

class BillingAddress(models.Model):
    """ This model stores the billing address of an order """
    order = models.OneToOneField(Order,on_delete = models.CASCADE,null = True)
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    company_name = models.CharField('Company Name (Optional)',max_length = 100,null = True,blank = True)
    state_or_country = models.CharField("State/Country",max_length = 100)
    town_or_city = models.CharField("Town/City",max_length = 100)
    phone = models.CharField(max_length = 50)
    email = models.EmailField()
    post_or_zipcode = models.CharField("Postcode/ZIP",max_length = 50)
    
    def __str__(self):
        return f"Order {self.order.id} Billing Address"
    
class Payment(models.Model):
    """ This is a model that stores payment details of a transaction """
    order = models.OneToOneField(Order,on_delete = models.CASCADE)
    reference = models.CharField(max_length = 100)
    amount = models.DecimalField(max_digits = 20,decimal_places = 2)
    
    def __str__(self):
        return f"Payment for Order {self.order.id}"

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'app\bootstrap.min.css' %}">
    <style>
        /* width */
        ::-webkit-scrollbar {
          width: 8px;
        }

        /* Track */
        ::-webkit-scrollbar-track {
          background: #f1f1f1;
        }

        /* Handle */
        ::-webkit-scrollbar-thumb {
          background: #888;
        }

        /* Handle on hover */
        ::-webkit-scrollbar-thumb:hover {
          background: #333333;
        }
        /* Nav Bar Designs */
        nav{
            background-color: #333333;
            position: fixed;
            width: 100%;
            padding: 10px 0px;
            top: 0px;
            z-index: 20;
        }
        nav .container-md > a{
            font-size: 25px;
            color: #159fdc;
        }
        nav .container-md > a:hover{
            text-decoration: none;
        }
        
        /* Options */
        #options{
            display: inline-block;
            float: right;
        }
        #options div{
            display: inline-block;
            margin: 0px 5px;
        }
        /* Cart */
        #options #cart{
            position: relative;
        }
        #options a{
            color: #159fdc;
            font-size: 13px;
            text-align: center;
        }
        #options a:hover{
            text-decoration: none;
        }
        #options #cart > a > span{
            position: absolute;
            color: white;
            background: #159fdc;
            padding: 1.5px;
            text-align: center;
            border-radius: 20px;
            font-size: 11px;
            line-height: 13px;
            right: 4px;
            bottom: 40px;
            
        }
        /* Search bar container */
        #search-container{
/*            background: red;*/
            position: relative;
            margin-top: 20px;
        }
        #search-container > input[type = 'text']{
            background-image: url("{% static 'app/images/search.png' %}");
            background-repeat: no-repeat;
            background-size: 20px;
            background-position: 5px center;
            border: thin solid #333333;
            border-radius: 10px;
            padding: 3px 10px 3px 30px;
            color: #777;
            font-size: 1.1rem;
            width: 100%;
        }
        #search-container > input[type = 'text']:focus{
            outline: none;
        }
        /* Dont forget to activate it when you are donw */
        #search-container > div{
            width: 100%;
            background: white;
            position: absolute;
            top: 33px;
            border-radius: 10px;
            border: thin solid rgba(0,0,0,.125);
            box-shadow: 0px 1px 5px rgba(0,0,0,.1);
            overflow: hidden;
            display: none;
        }
        #search-container > div > span{
            display: block;
            padding: 5px 15px;
            color: #535353
        }
        #search-container > div > p{
            font-size: 20px;
            text-align: center;
            margin: 20px auto;
        }
        #search-container > div > span:hover{
            text-decoration: none;
            background: rgba(0,0,0,.2)
        }
        
        /* Media query from 0px - 500px */
        @media only screen and (max-width:500px){
            /* Nav Bar */
            nav{
                padding: 5px 0px;
            }
            nav .container-md > a{
                font-size: 20px;
                line-height:35px;
            }
            
            /* Options */
            #options a{
                font-size: 12px;
                text-align: center;
            }
            #options div > a > img{
                width: 20px;
            }
            /* Cart */
            #options #cart > a > span{
                line-height: 13px;
                font-size: 11px;
                padding: 1px;
                border-radius: 5px;
                bottom: 35px;
                right: 3px;
            }
            
            /* Search Bar */
            #search-container > input[type = 'text']{
                background-size: 15px;
                background-position: 5px center;
                padding: 3px 10px 3px 25px;
                font-size: 1rem;
            }
            #search-container > div > span{
                font-size: .8rem;
            }
            #search-container > div > p{
                font-size: 16px;
            }
            #search-container > div{
                top: 31px;
            }
        }
        /* Media query from 0px - 350px */
        @media only screen and (max-width:400px){
            nav .container-md > a{
                font-size: 15px;
            }
        }
    </style>
    {% block head %}
    {% endblock %}
</head>
<body>
    <!-- Nav Bar -->
    <nav>
        <div class="container-md">
            <a href="{% url 'app:home' %}">Ogocando Commodities</a>
            <div id="options" class="text-center">
                {% if user.is_authenticated %}
                   <!-- User -->
                    <div>
                      <a href="{% url 'user:profile' %}">
                          <img width="28px" src="{% static 'app/images/user-hover.png' %}" alt=""><br/>
                           Hi {{ user.username }}
                      </a>
                   </div>
                {% endif%}
                <!-- Cart -->
               <div id="cart">
                  <a href="{% url 'app:cart' %}">
                      <img width="28px" src="{% static 'app/images/cart-hover.png' %}" alt=""><br/>
                       <span>{{ cart_items_count }}</span>
                       Cart
                  </a>
               </div>
               {% if user.is_authenticated %}
                  <!-- Log out -->
                   <div>
                      <a href="{% url 'user:logout' %}">
                          <img width="28px" src="{% static 'app/images/logout.png' %}" alt=""><br/>
                           Log Out
                      </a>
                   </div>
               {% else %}
                  <!-- Sign In -->
                   <div>
                      <a href="{% url 'user:signin' %}">
                          <img width="28px" src="{% static 'app/images/signin.png' %}" alt=""><br/>
                           Sign In
                      </a>
                   </div>
                   <!-- Sign Up -->
                   <div>
                      <a href="{% url 'user:signup' %}">
                          <img width="28px" src="{% static 'app/images/signup.png' %}" alt=""><br/>
                           Sign Up
                      </a>
                   </div>
               {% endif %}
            </div>
            <!-- Seach Bar -->
            <div id="search-container">
                <input id="search" type="text" name="search" placeholder="Try Cocoyam..">
                <!-- Search Results Container -->
                <div>
                </div>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script src = "{% static 'app\jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'app\bootstrap.bundle.min.js' %}"></script>
    <script>
        // A function that searches for goods
        let searchBar = () => {
            $('#search').keyup(function(e){
                let q = $(this).val();
                if(q){
                    $.ajax({
                        url: "{% url 'app:search' %}",
                        data: {
                            q
                        },
                        dataType: 'json',
                        success: function(data){
                            // Remove old search results
                            $('#search-container > div').empty();
                            $('#search-container > div').css('display','block');
                            if(data['results']){
                                for(let product of Object.keys(data['products'])){
                                    let productId = data.products[product];
                                    $('#search-container > div').append(
                                        `<span id = "${productId}">${product}</span>`
                                    );
                                }
                                // Redirect the page
                                $('#search-container > div > span').click(function(){
                                    let pId = $(this).attr('id');
                                    window.location.href = `http://localhost:8000/product/${pId}/detail`
                                    console.log("alright")
                                });
                            }
                            else{
                                $('#search-container > div').append(
                                    `<p>No Search Results</p>`
                                );
                            }
                        }
                    });
                }
                else{
                    // Remove old search results
                    $('#search-container > div').empty();
                    $('#search-container > div').css('display','none');
                }
            });
            // When the searchbar loses focus
            $('#search').blur(function(){
                // When the search bar isnt focused on
                setTimeout(function(){
                  $('#search-container > div').css('display','none');  
                },1000);
            });
        }
        searchBar()
    </script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

app/templates/app/checkout.html
{% extends 'app/base.html' %}


{% block head %}
    <title>Checkout</title>
    <style>
        input[type = 'submit']{
            color: #333333;
            background: #159fdc;
            transition: all .2s ease-in-out;
            border-radius: 2px;
        }
        input[type = 'submit']:hover{
            color: #159fdc;
            background: #333333;
        }
        /* Seperations */
        .sep-1, .sep-2{
            display: grid;
            grid-template-columns: 1.5fr 1fr;
        }
        .sep-1 > p:last-child, .sep-2 > p:last-child{
            text-align: right;
        }
        .sep-1 p{
            color: #333333;
        }
        .sep-2 p{
            font-size: 13px;
            color: lightslategray;
        }
        .sep-1:last-child p{
            color: #159fdc;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid" style="margin-top: 120px">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                      <form action="." method="post">
                         <p id="form-error" class = 'alert'></p>
                          {% csrf_token %}
                          <!-- Total -->
                          <input type="hidden" name="total">
                          <!-- Payment Reference -->
                          <input type="hidden" name="reference">
                          <div class="row">
                            {% for field in form %}
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        {{field.label_tag}}
                                        {{field}}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div style = 'max-width: 400px;margin: 20px auto'>
                            <input type="submit" id="pay" value="Continue To Payment" class="btn btn-block">
                        </div>
                      </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mt-5 mt-md-0 mb-5 mb-md-0">
                <div class="card" style="border: thin dashed lightslategray">
                    <div class="card-body">
                        <p>Your Order</p>
                        <hr class="border-secondary">
                        <div class="sep-1">
                            <p>Product</p>
                            <p>Total</p>
                        </div>
                        {% for good in cart_items %}
                            <div class="sep-2">
                                <p>{{ good.product.name }}</p>
                                <p class="good {{good.quantity}}-{{good.product.price}}"></p>
                            </div>
                        {% endfor %}
                        <hr>
                        <div class="sep-1">
                            <p>Subtotal:</p>
                            <p id="subtotal"></p>
                        </div>
                        <hr>
                        <div class="sep-2">
                            <p>Shipping:</p>
                            <p>Free Shipping</p>
                        </div>
                        <hr>
                        <div class="sep-1">
                            <p>Total</p>
                            <p id="total"></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
   <script src="https://js.paystack.co/v1/inline.js"></script>
    <script>
        // A function that invokes when the page reloads
        let callWhenPageReloads = () => {
            let cartSubtotal = 0;
            // Subtotal for each good
            $('.good').each(function(){
                let subtotal = Number($(this).attr('class').slice(5,).split('-')[0]) * Number($(this).attr('class').slice(5,).split('-')[1]);
                cartSubtotal += subtotal;
                subtotal = String(subtotal).split('.');
                if(subtotal.length > 1){
                    subtotal[1] = subtotal[1].slice(0,2).padEnd(2,'0');
                }
                else{
                    subtotal.push('00');
                }
                $(this).html(`GHC ${subtotal.join('.')}`);
            });
            
            // Subtotal for all the goods in the cart
            cartSubtotal = String(cartSubtotal).split('.');
            if(cartSubtotal.length > 1){
                cartSubtotal[1] = cartSubtotal[1].slice(0,2).padEnd(2,'0');
            }
            else{
                cartSubtotal.push('00');
            }
            $('#subtotal').html(`GHC ${cartSubtotal.join('.')}`);
            
            // Total for all the items in the cart and the shipping fees
            $('#total').html(`GHC ${cartSubtotal.join('.')}`);
            $('input[name = total]').val(cartSubtotal.join('.'));
        }
        callWhenPageReloads()

        // A function that allows the user to make payments
        let payment = () => {
            $('#pay').click(function(ele){
                ele.preventDefault();
                let emailRegex = /^[a-zA-Z][a-zA-Z\d]+@[a-z]+\.[a-z]{3}(\.[a-z]{2,6})?$/;
                // Get the form data
                let firstName = $('#id_first_name').val();
                let lastName = $('#id_last_name').val();
                let country = $('#id_state_or_country').val();
                let town = $('#id_town_or_city').val();
                let phone = $('#id_phone').val();
                let email = $('#id_email').val();
                if(firstName && lastName && country && town && phone && emailRegex.test(email)){
                    console.log("Alright");
                    // Total
                    let total = Number($('input[name = total]').val()) * 100;
                    let form = $(this).parents('form');
                    // Submit the form
//                    form.submit()
                    console.log(total);
//                     Pay through paystack
                    let handler = PaystackPop.setup({
                        key: "pk_test_dd1150330d138de167b39d9be0b180ee8b10319f",
                        email: email,
                        currency: 'GHS',
                        channels: ['card','mobile_money'],
                        amount: total,
                        callback: function(response){
                            if(response.reference){
                                // Get the transaction reference
                                $('input[name = reference]').val(response.reference);
                                // Submit the form
                                form.submit();
                            }
                        }
                    });

                    handler.openIframe();
                }
                else{
                    $('#form-error').text("Make sure you have provided the appropriate information for the input fields.").addClass('alert-danger');
                }
            });
        }
        payment();
    </script>
{% endblock %}

app/templates/app/orders.html
{% extends 'app/base.html' %}
{% load static %}

{% block head %}
    <title>Orders</title>
    <style>
        /* Main Menu */
        #main-menu{
            width: calc(100% - 170px);
            margin: auto;
/*            height: 200px;*/
/*            background: lime;*/
            display: inline-block;
            position: relative;
            left: 160px;
            transition: all .2s ease-in-out;
        }
        #main-menu > ul > li >a:hover{
            text-decoration: none;
        }

        /* No Item */
        #no-item > div > a{
            color: #333333;
            background: #159fdc;
            transition: all .2s ease-in-out;
            border-radius: 2px;
        }
        #no-item > div > a:hover{
            color: #159fdc;
            background: #333333;
            box-shadow: 0px 5px 25px rgba(0,0,0,.3)
        }
        
        
        /* Side Menu */
        #side-menu{
            width: 150px;
            position: fixed;
            height: 100vh;
/*            border-right: thin solid rgba(0,0,0,.125);*/
            left: 0px;
            top: 120px;
/*            border: thin solid red;*/
            transition: all .2s ease-in-out;
        }
        #side-menu a{
            display: block;
            text-align: center;
            padding: 10px 0px;
            color: lightslategray;
            font-weight: 500;
        }
        #side-menu a:hover{
            text-decoration: none;
            color: #159fdc;
        }
        #side-menu #active{
            border-right: medium solid #159fdc;
            color: #159fdc;
        }
        /* Hide Small Screen Icons */
        #side-menu a.small-screen-item-link{
            display: none;
        }
        
        /* Media query from 0px - 500px */
        @media only screen and (max-width:500px){
            /* Side Menu */
            #side-menu{
                width: 50px;
            }
            #side-menu h5, #side-menu a{
                display: none;
            }
            #side-menu > a.small-screen-item-link{
                display: block;
            }
            /* Main Menu */
            #main-menu{
                width: calc(100% - 60px);
                left: 55px;
            }
        }
    </style>
{% endblock %}
{% block content %}
    <div id="wrapper" style = 'margin-top: 120px;'>
        <div id="side-menu">
            <h5 class="text-center text-dark">Orders</h5>
            <!-- Big Screen -->
            <a href="{% url 'user:profile' %}">User Info</a>
            <a href="{% url 'app:cart' %}">Cart &nbsp; <span class="badge badge-dark">{{ cart_items_count }}</span></a>
            <a href="{% url 'app:orders' %}" id ='active'>Orders &nbsp; <span class="badge badge-dark">{% firstof user.order_set.count '0' %}</span></a>
            <a href="{% url 'user:logout' %}" style="color: red;">Logout</a>
            <!-- Small Screen -->
            <a href="{% url 'user:profile' %}" class = 'small-screen-item-link'>
                <img width="40px" src="{% static 'app/images/user-profile.png' %}" alt="Profile">
            </a>
            <a href="{% url 'app:cart' %}" class = 'small-screen-item-link'>
               <img width="40px" src="{% static 'app/images/cart-small.png' %}" alt="Cart">
            </a>
            <a href="" class = 'small-screen-item-link' id="active" >
                <img width="40px" src="{% static 'app/images/order.png' %}" alt="Orders">
            </a>
            <a href="{% url 'user:logout' %}" class = 'small-screen-item-link' >
                <img width="40px" src="{% static 'app/images/logout-small.png' %}" alt="Logout">
            </a>
        </div>
        <div id="main-menu">
            {% if orders %}
                <ul class="list-group" style="box-shadow: 0px 2px 5px rgba(0,0,0,.2)">
                    {% for order in orders %}
                        <li class="list-group-item">
                            <a href="">
                               <div class="row">
                                    {% for orderitem in order.orderitem_set.all %}
                                        <div class="col-sm-6 d-flex mt-2 align-items-top col-lg-4">
                                            <img style="width: 100px;height: 80px;" src="{{orderitem.product.image1.url}}" alt="">
                                            <span class="text-dark ml-2" style="font-weight: 500;">{{orderitem.product.name|truncatechars:'30'}}</span>
                                        </div>
                                    {% endfor %}
                                </div>
                                <p class="text-muted m-auto">
                                    {{ order.date|date:'jS M, Y' }} - {{ order.date|time:'g:i.sa' }}&nbsp;&nbsp;&nbsp;
                                    {% if order.delivered %}
                                        <span class="badge badge-success">Delivered</span>
                                    {% else %}
                                        <span class="badge badge-info">Not Delivered</span>
                                    {% endif %}
                                </p>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div id = 'no-item'>
                    <h3 class="text-muted text-center mt-5">Sorry! You haven't made any orders yet...</h3>
                    <div style="max-width: 400px;margin: 20px auto">
                        <a href="{% url 'app:home' %}" class = 'btn btn-block'>Continue Shopping</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block javascript %}
{% endblock %}